app/checkout/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, BooleanField
from wtforms.validators import DataRequired, Length, Optional, Regexp

class CheckoutForm(FlaskForm):
    address = StringField("Adres", validators=[DataRequired(), Length(max=255)])
    city = StringField("Miasto", validators=[DataRequired(), Length(max=100)])
    postal_code = StringField("Kod pocztowy", validators=[DataRequired(), Length(max=20)])
    payment_method = SelectField('Metoda płatności',choices=[('card', 'Karta'), ('blik', 'BLIK'), ('pbr', 'Za pobraniem')],validators=[DataRequired()])
    delivery_method = SelectField('Metoda dostawy',choices=[('inpost', 'InPost'), ('dhl', 'DHL'), ('poczta', 'Poczta Polska')],validators=[DataRequired()])
    card_number = StringField('Numer karty', validators=[Optional(), Length(min=16, max=19)])
    expiration_date = StringField('Data ważności',validators=[Optional(), Regexp(r'^\d{2}/\d{2}$', message="Format MM/YY")])
    cvv = StringField('CVV', validators=[Optional(), Length(min=3, max=4)])
    blik_code = StringField('Kod BLIK',validators=[Optional(), Length(min=6, max=6, message="Kod BLIK musi mieć 6 cyfr")])
    use_default_address = BooleanField('Użyj domyślnego adresu')
    submit = SubmitField("Złóż zamówienie")

    def validate(self, extra_validators=None):


        initial_validation = super(CheckoutForm, self).validate(extra_validators=extra_validators)
        if not initial_validation:
            return False

        if self.payment_method.data == 'card':
            if not self.card_number.data or not self.expiration_date.data or not self.cvv.data:
                if not self.card_number.data:
                    self.card_number.errors.append('Numer karty jest wymagany przy płatności kartą.')
                if not self.expiration_date.data:
                    self.expiration_date.errors.append('Data ważności jest wymagana przy płatności kartą.')
                if not self.cvv.data:
                    self.cvv.errors.append('CVV jest wymagany przy płatności kartą.')
                return False

        elif self.payment_method.data == 'blik':
            if not self.blik_code.data:
                self.blik_code.errors.append('Kod BLIK jest wymagany przy płatności BLIK.')
                return False

        return True

app/checkout/__init__.py
from flask import Blueprint

bp = Blueprint('checkout', __name__)

from app.checkout import routes

app/checkout/routes.py
from app.checkout import bp
from app import db
import sqlalchemy as sa
from app.models import Part, Cart, CartItem, Order, OrderItem
from flask import render_template, request, redirect, flash, url_for
from flask_login import login_required, current_user
from app.checkout.forms import CheckoutForm



@bp.route('/checkout', methods=['POST'])
@login_required
def checkout():
    #print(f"DEBUG: request.form = {request.form}")  # Dodaj na początku funkcji
    user = current_user

    if not user.cart or not user.cart.items:
        flash("Twój koszyk jest pusty!", "warning")
        return redirect(url_for('cart.view_cart'))

    form = CheckoutForm()
    #print(f"DEBUG: form.validate_on_submit() = {form.validate_on_submit()}")  # Dodaj debugowanie
    if form.validate_on_submit():
        payment_method = request.form.get('payment_method')
        delivery_method = form.delivery_method.data
        #print(f"DEBUG: payment_method (from request.form) = {payment_method}")
        if form.use_default_address.data:
            address = user.address
            city = user.city
            postal_code = user.postal_code
        else:
            address = form.address.data
            city = form.city.data
            postal_code = form.postal_code.data


        # Utwórz zamówienie
        order = Order(
            user=user,
            address=form.address.data,
            city=form.city.data,
            postal_code=form.postal_code.data,
            status='pending',
            payment_method = payment_method,
            delivery_method = delivery_method
        )
        db.session.add(order)

        cart_items_query = sa.select(CartItem).where(CartItem.cart_id == user.cart.id)
        cart_items = db.session.scalars(cart_items_query).all()

        for cart_item in cart_items:
            order_item = OrderItem(
                order=order,
                part=cart_item.part,
                quantity=cart_item.quantity,
            )
            db.session.add(order_item)

        if not user.cart.items:
            flash("Twój koszyk jest pusty!", "warning")
            return redirect(url_for('cart.cart'))

        # Usuń przedmioty z koszyku uzytkownika
        db.session.query(CartItem).filter_by(cart_id=user.cart.id).delete()
        db.session.commit()

        if payment_method == 'card':
            flash("Platnosc karta powiodla sie", "info")
            # Tutaj kod do przekierowania do bramki płatności
            return redirect(url_for('checkout.view_orders', order_id=order.id))  # Przykładowe przekierowanie
        elif payment_method == 'blik':
            flash("Platnosc blikiem powiodla sie", "info")
            # Tutaj kod do wygenerowania kodu BLIK i wyświetlenia instrukcji
            return redirect(url_for('checkout.view_orders', order_id=order.id))
        elif payment_method == 'pbr':
            #print("DEBUG: Obsługa płatności za pobraniem")  # Dodaj debugowanie
            flash("Zamówienie za pobraniem zostało złożone.", "success")
            return redirect(url_for('checkout.view_orders'))
        else:
            flash("Nieznana metoda płatności", "error")
            return redirect(url_for('cart.view_cart'))
    address_data_present = bool(user.address and user.city and user.postal_code)
    return render_template('checkout/checkout.html',form=form,address_data_present=address_data_present)


@bp.route('/orders', methods=['GET'])
@login_required
def view_orders():
    user = current_user
    orders = Order.query.filter_by(user_id=user.id).order_by(Order.created_at.desc()).all()
    return render_template('orders/orders.html', orders=orders)

app/templates/checkout/checkout.html
{% extends "base.html" %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }

        .card {
            border-radius: 10px;
            background: #ffffff;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .card-body {
            padding: 4rem;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form-label {
            font-weight: bold;
        }

        .form-control {
            border-radius: 5px;
            border: 1px solid #b2bec3;
            padding: 10px;
        }

        .form-control:focus {
            border-color: #56a8e7;
            box-shadow: 0 0 0 0.2rem rgba(116, 117, 119, 0.25);
        }

        .btn-primary {
            background: #1677c9;
            border: none;
            padding: 15px 25px;
            border-radius: 5px;
            font-size: 1rem;
            font-weight: bold;
            transition: background 0.3s;
            display: inline-block;
            text-align: center;
        }

        .btn-primary:hover {
            background: #597a9f;
        }

        a.text-primary {
            color: #1677c9;
            font-weight: bold;
        }

        a.text-primary:hover {
            color: #143060;
        }

        .text-danger {
            font-size: 0.9rem;
            margin-top: 0.5rem;
        }
        .text-center {
            margin-bottom: 0.8rem;
            display: flex;
            justify-content: center;
            width: 100%;
        }
    </style>
    <div class="container">
        <div class="card">
            <div class="card-body">


            <h1>Checkout</h1>
            <p>Proszę wypełnić dane zamówienia:</p>

            <form method="POST" action="{{ url_for('checkout.checkout') }}">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    <label for="address">Adres:</label>
                    {{ form.address(class="form-control", id="address") }}
                </div>

                <div class="form-group">
                    <label for="city">Miasto:</label>
                    {{ form.city(class="form-control", id="city") }}
                </div>

                <div class="form-group">
                    <label for="postal_code">Kod pocztowy:</label>
                    {{ form.postal_code(class="form-control", id="postal_code") }}
                </div>

                <div class="form-group">
                    {{ form.use_default_address.label }}
                    {{ form.use_default_address(id="use_default_address", disabled= (not current_user.address or not current_user.city or not current_user.postal_code) ) }}
                </div>

                <div class="form-group">
                    <label for="payment_method">Metoda płatności:</label>
                    <select name="payment_method" id="payment_method" class="form-control">  <option value="card">Karta</option>
                        <option value="blik">BLIK</option>
                        <option value="pbr">Za pobraniem</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="delivery_method">Metoda dostawy:</label>
                    {{ form.delivery_method(class="form-control") }}
                </div>

                <div class="form-group card-details" style="display: none;">
                    <label for="card_number">Numer karty:</label>
                    <input type="text" name="card_number" id="card_number" class="form-control">
                </div>

                <div class="form-group card-details" style="display: none;">
                    <label for="expiration_date">Data ważności:</label>
                    <input type="text" name="expiration_date" id="expiration_date" class="form-control" placeholder="MM/YY">
                </div>

                <div class="form-group card-details" style="display: none;">
                    <label for="cvv">CVV:</label>
                    <input type="text" name="cvv" id="cvv" class="form-control">
                </div>

                <div class="form-group blik-details" style="display: none;">
                    <label for="blik_code">Kod BLIK:</label>
                    <input type="text" name="blik_code" id="blik_code" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary text-center">{{ form.submit.label }}</button>
            </form>
            </div>
        </div>
    </div>

<script>
    $(document).ready(function() {
        const paymentMethodSelect = $('#payment_method');
        const cardDetails = $('.card-details');
        const blikDetails = $('.blik-details');
        const useDefaultAddressCheckbox = $('#use_default_address');

        function toggleFields() {
            if (paymentMethodSelect.val() === 'card') {
                cardDetails.show();
                blikDetails.hide();
            } else if (paymentMethodSelect.val() === 'blik') {
                cardDetails.hide();
                blikDetails.show();
            } else {
                cardDetails.hide();
                blikDetails.hide();
            }
        }

        function fillAddressFields() {
            if (useDefaultAddressCheckbox.is(':checked') && !useDefaultAddressCheckbox.is(':disabled')) {
                $('#address').val('{{ current_user.address }}');
                $('#city').val('{{ current_user.city }}');
                $('#postal_code').val('{{ current_user.postal_code }}');
            } else {
                $('#address').val('');
                $('#city').val('');
                $('#postal_code').val('');
            }
        }


        paymentMethodSelect.on('change', toggleFields);
        useDefaultAddressCheckbox.on('change', fillAddressFields);
        toggleFields();
        fillAddressFields();
    });
</script>
{% endblock %}